config/routes.rb
Trackdb::Application.routes.draw do
  devise_for :users

  root :to => 'urls#welcome'
  
  get "urls/_search"
  get "urls/_search2"

  get "urls/index"
  get "urls/new"
  get "urls/search"
  get "urls/search2"
  get "urls/welcome"
  match '/search' => 'urls#search'
  match '/search2' => 'urls#search2'

  
  resources :urls do
    collection { post :import }
  end

  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/url.rb
class Url < ActiveRecord::Base
	
  attr_accessible :order_number, :url1, :url2, :url3, :url4, :url5, :email, :custref, :date, :trader_code, :trader_name

def self.import(file)
  	CSV.foreach(file.path, headers: true) do |row|
  		Url.create! row.to_hash
  	end
  end

belongs_to :user




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :phone_number, :company
  # attr_accessible :title, :body

  has_many :urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/urls_controller.rb
require 'csv'
class UrlsController < ApplicationController



  def index
    @url = Url.order("urls.date DESC")
  end

  def welcome
    @url = Url.all
  end

  def new
    @url = Url.new#(:title => 'default')
  end

  def create
    @url = Url.new(params[:url])
    if @url.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def show
    @url = Url.find(params[:id])
  end

  def import
    Url.import(params[:file])
    flash[:notice] = "Uploaded Successfully"
    redirect_to :action => 'welcome'
  end

  

  def search
    @search_term = params[:q]
    st = "%#{params[:q]}%"
    @url = Url.where("email ILIKE ? || '%' or custref ILIKE ? or order_number ILIKE ? or url4 ILIKE ? or trader_code ILIKE ? or trader_name ILIKE ?", st, st, st, st, st, st).order("date DESC").page(params[:page]).per_page(25)

    respond_to do |format|
      format.html
      format.json {render json: @url}
    end
  end

  def search2
    @search_term = params[:q]
    st = "%#{params[:q]}%"
    @url = Url.where("email ILIKE ? or custref ILIKE ?", st, st).order("date DESC").page(params[:page]).per_page(25)

    respond_to do |format|
      format.html
      format.json {render json: @url}
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trade Supply Order Tracking</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Rokkitt' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div id="header">
  <div class="middle">
    <div id="head1"><%= image_tag "/assets/tradesupplylogo.png" %></div>
    <div id="head2"><h1 style="color: #fff;">Next Day Delivery<br />
      anywhere in Ireland &amp; UK</h1></div>
    <div id="head3"><div class="ordertracking"><h3>Order Tracking</h3>

      <% if user_signed_in? %>
        <%= current_user.email %><br />
      <% end %>

      </div></div>

  </div>
</div>


<div class="middle top">

      <ul id="nav">
        <li><a href="http://www.tradesupply.eu">Home</a></li>
        <li><%= link_to "Track", urls_welcome_path %>
          <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to('Register', new_user_registration_path) %></li>
        
        <% end %>
      </ul>


 

<% if !flash.blank? %>
<div class="errors">
<%= flash[:notice] %>
<%= flash[:alert] %>
</div>
<% end %>


	<%= yield %>
</div>

<div style="clear:both" class="middle">
<div id="pwdby">

<div id="pwdbyLeft">
      Powered By
</div>

<div id="pwdbyRight">
  <a target="_blank" href="http://www.supportsolutions.ie/"><img height="30px" src="/assets/support_logo.jpg"></a>
</div>

  </div>
</div>

</body>
</html>

app/views/urls/_search.html.erb
<%= form_tag("/search", :method => "get") do %>

<%= label_tag(:q, "") %>
<%= text_field_tag(:q) %>
<%= submit_tag "Search" %>

<% end %>

app/views/urls/_search2.html.erb
<%= form_tag("/search2", :method => "get") do %>

<%= label_tag(:q, "") %>
<%= text_field_tag(:q) %>
<%= submit_tag "Search" %>

<% end %>

app/views/urls/index.html.erb
<div>
	<div class="span6">

<h2>Database entries</h2><br /><br />
<%= link_to("Add new Url", {:action => 'new'}, :class => 'btn btn-danger') %><br /><br />

<table>


<% @url.each do |u| %>

<ul class="well">
	<li><%= u.order_number %></li>
	<li><%= u.url1 %></li>
	<li><%= u.url2 %></li>
	<li><%= u.url3 %></li>
	<li><%= u.url4 %></li>
	<li><%= u.url5 %></li>
	<li><%= u.email %></li>
	<li><%= u.date %></li>
	<li><%= u.custref %></li>
	<li><%= u.trader_code %></li>
	<li><%= u.trader_name %></li>
</ul>

	<script>
    	var hash = hex_md5("<%= u.url2 %>");
    	var hash2 = ("<%= u.url1 %>" + hash + "<%= u.url3 %><%= u.url4 %><%= u.url5 %>");
    	document.write("<a class='btn btn-info' href= <%= u.url1 %>" + hash + "<%= u.url3 %><%= u.url4 %><%= u.url5 %>" + ">" + "Link" + "</a>")
	</script>


<% end %>

</table>

	</div>

<% if user_signed_in? %>
	<div class="span6">
		<div>
			<%= render :partial => 'urls/search' %>
		</div>
<% end %>
		<h2>Upload file</h2>

		<%= form_tag import_urls_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Submit" %>
		<% end %>
	</div>
</div><!--row-->

app/views/urls/new.html.erb
<h2>New Url</h2>

<%= form_for(:url, :url => {:action => 'create'}) do |f| %>

<table>

<tr>
	<th>order_number</th>
	<td><%= f.text_field(:order_number) %></td>
</tr>
<tr>
	<th>Url1</th>
	<td><%= f.text_field(:url1) %></td>
</tr>
<tr>
	<th>Url2</th>
	<td><%= f.text_field(:url2) %></td>
</tr>
<tr>
	<th>Url3</th>
	<td><%= f.text_field(:url3) %></td>
</tr>
<tr>
	<th>Url4</th>
	<td><%= f.text_field(:url4) %></td>
</tr>
<tr>
	<th>Url5</th>
	<td><%= f.text_field(:url5) %></td>
</tr>
<tr>
	<th>Email</th>
	<td><%= f.text_field(:email) %></td>
</tr>
<tr>
	<th>Date</th>
	<td><%= f.text_field(:date) %></td>
</tr>
<tr>
	<th>Customer Ref</th>
	<td><%= f.text_field(:custref) %></td>
</tr>
<tr>
	<th>Trader Coded</th>
	<td><%= f.text_field(:trader_code) %></td>
</tr>
<tr>
	<th>Trader Name</th>
	<td><%= f.text_field(:trader_name) %></td>
</tr>

</table>

<div>
<%= submit_tag("Create Url") %>
</div>

<% end %>

app/views/urls/search.html.erb
<div class="flickr_pagination">
    <%= will_paginate @url %>
  </div>
    


<div>

<h1 style="text-align:center">Search Result</h1><br />

<h3 style="text-align:center">Searching For: <%= @search_term %></h3>

<table class="searchTable">

<% if @url.length == 0 %><br />
<h2>No Items found for this search term</h2>
<% end %>

	<tr class="trtop">
		<th>Date</th>
		<th>Email</th>
		<th>Your Order Number</th>
		<th>Our Order Number</th>
		<th>Our Delivery Number</th>
		<th>Account Code</th>
		<th>Company Name</th>
		<th>GLS</th>
	</tr>

<% @url.each do |u| %>

<tr>
	<td><%= u.date %></td>
	<td><%= u.email %></td>
	<td><%= u.custref %></td>
	<td><%= u.order_number %></td>
	<td><%= u.url4 %></td>
	<td><%= u.trader_code %></td>
	<td><%= u.trader_name %></td>
	<td><script>
    	var hash = hex_md5("<%= u.url2 %>");
    	var hash2 = ("<%= u.url1 %>" + hash + "<%= u.url3 %><%= u.url4 %><%= u.url5 %>");
    	document.write("<a target='_blank' href= <%= u.url1 %>" + hash + "<%= u.url3 %><%= u.url4 %><%= u.url5 %>" + ">" + "Track" + "</a>")
	</script></td>
</tr>



<% end %> 

</table>

</div>

app/views/urls/search2.html.erb
<div class="flickr_pagination">
    <%= will_paginate @url %>
  </div>
    
<div class="welcomeContainer">

<div>

<h1 style="text-align:center">Search Result</h1><br />

<h3 style="text-align:center">Searching For: <%= @search_term %></h3>

<table class="searchTable">

<% if @url.length == 0 %><br />
<h2>No Items found for this search term</h2>
<% end %>

	<tr class="trtop">
		<th>Date</th>
		<th>Email</th>
		<th>Your Order Number</th>
		<th>Our Order Number</th>
		<th>Our Delivery Number</th>
		<th>Account Code</th>
		<th>Company Name</th>
		<th>GLS</th>
	</tr>

<% @url.each do |u| %>

<tr>
	<td><%= u.date %></td>
	<td><%= u.email %></td>
	<td><%= u.custref %></td>
	<td><%= u.order_number %></td>
	<td><%= u.url4 %></td>
	<td><%= u.trader_code %></td>
	<td><%= u.trader_name %></td>
	<td><script>
    	var hash = hex_md5("<%= u.url2 %>");
    	var hash2 = ("<%= u.url1 %>" + hash + "<%= u.url3 %><%= u.url4 %><%= u.url5 %>");
    	document.write("<a target='_blank' href= <%= u.url1 %>" + hash + "<%= u.url3 %><%= u.url4 %><%= u.url5 %>" + ">" + "Track" + "</a>")
	</script></td>
</tr>



<% end %> 

</table>

</div>

</div>

app/views/urls/welcome.html.erb
<div class="welcomeContainer">

<h2 style="text-align:center;margin-bottom:15px !important;">Welcome to the tracking section for Trade Supply.</h2>

<% if current_user.try(:admin?) %>
<div class="searchContainer">
		<div class="searchBox">
			<h3 class="h2Upload">Search by:</h3><p style="text-align: center">Email / Order Number / Delivery Number / Account Code / Company Name</p> <br />
			<%= render :partial => 'urls/search' %>
		</div><!--searchBox-->
</div><!--searchContainer-->

<% else %>


<div class="searchContainer">
	<% if user_signed_in? %>
		<div class="searchBox">
			<h3 class="h2Upload">Search by:</h3><p style="text-align: center">Email / Order Number</p><br />
			<%= render :partial => 'urls/search2' %>
		</div><!--searchBox-->
<% else %>
	<div>
		<h2 class="h2center" style="text-align:center">Please Register / Sign In</h2>
	</div><!--div h2-->
</div><!--searchContainer-->
<% end %>

<% end %>





<% if current_user.try(:admin?) %>
<div id="uploadContainer">

	<div id="uploadBox">
		<h2 class="h2Upload">File Upload</h2>
		<%= form_tag import_urls_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Submit" %>
		<% end %>
	</div>

</div><!--uploadContainer-->
<% end %><!--if current admin-->

<div class="divider"></div>


<% if !user_signed_in? %>
<div class="videoCont">
<div class="video1">
	<h2 style="font-weight: bolder; text-align: center; font-size: 34px; line-height: 30px; text-decoration: underline;">Watch the Geting Started Video</h2>
<iframe src="http://fast.wistia.net/embed/iframe/yr0nfz0ng7" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="586" height="366"></iframe>
</div><!--video1-->
</div>
<% end %>


<% if current_user.try(:admin?) %>
<div class="videoCont">
<div class="video3">
	<h2 style="font-weight: bolder; text-align: center; font-size: 34px; line-height: 30px; text-decoration: underline;">Uploading file from Horizon to Ordertrax</h2>
<iframe src="http://fast.wistia.net/embed/iframe/jz26897kwz" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="586" height="366"></iframe>
</div><!--video1-->
</div>
<% end %>


<% if current_user.try(:admin?) %>
<div class="videoCont">
<div class="video2">
	<h2 style="font-weight: bolder; text-align: center; font-size: 34px; line-height: 30px; text-decoration: underline;">Searching for Orders on Ordertrax</h2>
<iframe src="http://fast.wistia.net/embed/iframe/ol9zxkdirl" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="586" height="366"></iframe>
</div><!--video1-->
</div>
<% end %>

</div><!--welcomeContainer-->


<script type="text/javascript">
jQuery(function(){
        $("input[value='Search']" ).click(function(){
        $(".error").hide();
        var hasError = false;
        var searchReg = /^(.*]{0,16})$/;
        var searchVal = $("#q").val();
        if(searchVal == '') {
            $("#q").after('<span class="error">Please enter a search term.</span>');
            hasError = true;
        } else if(!searchReg.test(searchVal)) {
            $("q").after('<span class="error">Enter valid text.</span>');
            hasError = true;
        }
        if(hasError == true) {return false;}
    });
});
</script>